# -*- coding: utf-8 -*-
"""Untitled87.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gbjz0IszWJrt5X-XkXjIdyjK-SOeK-i6
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io

filename = list(uploaded.keys())[0]
if filename.endswith('.csv'):
    df = pd.read_csv(io.BytesIO(uploaded[filename]))
elif filename.endswith('.xlsx'):
    df = pd.read_excel(io.BytesIO(uploaded[filename]))

df.head()  # Preview karo data

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util
import numpy as np

# Load the model
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# Rubric descriptions ko vector/embedding mein convert karo
descriptions = df['Description'].fillna('').tolist()
desc_embeddings = model.encode(descriptions)

# User input: yahan apna symptom hinglish ya english mein likho
user_input = "raat ko akela mehsoos karta hoon, kisi ki help nahi milti"

# User input ka embedding
input_embedding = model.encode([user_input])[0]

# Cosine similarity calculate karo
scores = util.cos_sim(input_embedding, desc_embeddings)[0].cpu().numpy()

# Top 3 ya jitne chaho best match nikal lo
top_n = 3
top_idx = np.argsort(scores)[-top_n:][::-1]

print("\nTop matched rubrics:")
for idx in top_idx:
    print(f"Rubric: {df.iloc[idx]['Rubric']}\nDescription: {df.iloc[idx]['Description']}\nScore: {scores[idx]:.2f}\n")

symptom_list = [
    "raat ko akela feel karta hoon, ghar ki yaad aati hai",
    "baat baat par gussa aata hai",
    "bahut chinta lagti hai bina wajah"
]

for user_input in symptom_list:
    input_embedding = model.encode([user_input])[0]
    scores = util.cos_sim(input_embedding, desc_embeddings)[0].cpu().numpy()
    top_idx = np.argsort(scores)[-3:][::-1]

    print(f"\nFor: {user_input}")
    for idx in top_idx:
        print(f"Rubric: {df.iloc[idx]['Rubric']}\nDescription: {df.iloc[idx]['Description']}\nScore: {scores[idx]:.2f}\n")

# Ye run karo agar runtime abhi bhi install ka error dikha raha hai:
!pip install sentence-transformers gradio --quiet

import pandas as pd
from sentence_transformers import SentenceTransformer, util
import gradio as gr
import numpy as np

# Assume df already loaded as shown pehle (jaise tumhare screenshot mein hai)
# Model load karo (pehli dafa ho sakta hai thoda time le)
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# Descriptions embedding
descriptions = df['Description'].fillna('').tolist()
desc_embeddings = model.encode(descriptions)

# Rubric matching function
def find_rubrics(symptom):
    input_embedding = model.encode([symptom])[0]
    scores = util.cos_sim(input_embedding, desc_embeddings)[0].cpu().numpy()
    top_n = 3
    top_idx = np.argsort(scores)[-top_n:][::-1]
    result = ""
    for idx in top_idx:
        result += f"Rubric: {df.iloc[idx]['Rubric']}\nDescription: {df.iloc[idx]['Description']}\nScore: {scores[idx]:.2f}\n\n"
    return result.strip()

iface = gr.Interface(
    fn=find_rubrics,
    inputs=gr.Textbox(lines=2, placeholder="Hinglish ya English mein symptom type karo..."),
    outputs="text",
    title="Homeopathy Rubric Finder",
    description="Symptom likho (Hinglish/English), yeh best matching rubric dega apke excel file se."
)

iface.launch()